### ISSUE TITLE
Add more decay types to the gen block

### ISSUE THREAD

**Issue by drkovalskyi** [drkovalskyi/Bmm5#5]
So far we cover mm, mmK and mmKK final states in genbmm block. @gandreassi what other channels do we need?

**Comment by gandreassi** [comment]
KPimumu (B->JpsiK*) might also come useful one day, although we don't strictly need it now.
On the other hand, we do need the MC truth information to work For all physics backgrounds: B->hh and part-reco like B->pi mu nu.

**Comment by drkovalskyi** [comment]
Here it's only about identifying events at gen level and storing the relevant info, i.e. do we want to track B->hh at gen level by itself?

**Comment by gandreassi** [comment]
Well what we need in the end is, for each B->mumu candidate, to be able to say "this was actually B->KPi" or rather "this is actually some mis-reconstructed stuff".  What I do with the signal is check the true ID of the two muons and of their mother particle. But with B->Kpi this doesn't work as muon true IDs are often 0.

**Comment by drkovalskyi** [comment]
This a gen block, i.e. something to answer a question like we have BtoKpi, did we get a BtoMuMu out of it or not. The other way around is a different issue.

**Comment by gandreassi** [comment]
Coming back on this: what we need is to be able to truth-match candidates for all the backgrounds.
I'm not sure if we need gen-block information for this.
What I do with the signal is just checking if the generated ID of the particles correspond to the reconstructed.

Backgrounds are:
BsToKPi
BdToKPi
BdToPiPi
BsToKK
BsToPiPi
BdToMuMuPi
BdToPiMuNu
BsToKMuNu
BuToMuMuPi
LambdaBToPK
LambdaBToPMuNu

**Comment by drkovalskyi** [comment]
For real muons reco to gen matching works. It won't match pion or kaon decays as well as random tracks. Anyway, this list is useful. I'll think how to make it work.

**Comment by gandreassi** [comment]
I would also add LambdaBToPPi to the list.  It's going to be very rare (bf is small and it requires double mis-ID), but if we look at LambdaBToPK we also want to look at this.

**Comment by drkovalskyi** [comment]
What about BcToJpsiMuNu? I see in LHCb plots. Not sure why it's relevant. The rest we have now.

**Comment by drkovalskyi** [comment]
All but Bc is implemented in d87043369b22abfbbd33b0af10197813d0191159

**Comment by gandreassi** [comment]
Yes, it would be good to study it.  We only have a 2018 sample for Bc, which I added to Kraken a few days ago. It may not enter the signal mass window at all, but it's to be seen.
